<a href="https://colab.research.google.com/github/B2BDA/Tensorflow_Basics_Templates/blob/main/Tensorflow_Basics_2_x.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [4]:
print(tf.__version__)

2.3.0


In tensorflow 2.x  there is no concept of session. Varaibles can be created using .variable(), .constant(). 

In [6]:
cons = tf.constant(10)
cons

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [7]:
var = tf.Variable(10)
var

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [10]:
tf.config.list_physical_devices('GPU')

[]

In [11]:
tf.constant([[1,2],[3,4]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [12]:
tf.constant([[1,2],[3,4]], dtype = tf.float32)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

Addition - Element wise

In [15]:
tf.add(tf.Variable([[1,2],[3,4]]),tf.Variable([[1,2],[3,4]]))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

Matrix Multiplication


In [17]:
tf.matmul(tf.Variable([[1,2],[3,4]]),tf.Variable([[1,2],[3,4]]))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

Random varaibles

In [18]:
tf.random.normal(shape = (2,2), mean = 0, stddev = 1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.46287465,  0.8723945 ],
       [ 1.1053027 ,  0.68376154]], dtype=float32)>

In [23]:
tf.random.uniform(shape = (2,2), minval = 0, maxval = 1, dtype = tf.float64)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.66522296, 0.99943558],
       [0.73554915, 0.38860229]])>

Reassigning a variable



In [24]:
var

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [25]:
var.assign(15)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=15>

In [27]:
var = tf.Variable([[1,2],[3,4]])
var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [30]:
var.assign_add([[5,6],[7,8]])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]], dtype=int32)>

In [47]:
tensor = tf.Variable([ [ [10., 11., 12.], [13., 14., 15.] ], [ [16., 17., 18.], [19., 20., 21.] ] ])
tensor.shape

TensorShape([2, 2, 3])

In [48]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)>

This tensor can be reshaped in any ways but it always has to be a factor of the multiplicationsof the dimensions ie 3*2*2 = 12 so 12!


In [35]:
tf.reshape(tensor, (6,2))

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[10., 11.],
       [12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.]], dtype=float32)>

In [36]:
tf.reshape(tensor, (2,6))

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)>

In [39]:
ten = tf.reshape(tensor, (4,3,1))
ten

<tf.Tensor: shape=(4, 3, 1), dtype=float32, numpy=
array([[[10.],
        [11.],
        [12.]],

       [[13.],
        [14.],
        [15.]],

       [[16.],
        [17.],
        [18.]],

       [[19.],
        [20.],
        [21.]]], dtype=float32)>

In [46]:
ten[2,1]

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([17.], dtype=float32)>

In [49]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)>

In [51]:
tensor[1,0,1]

<tf.Tensor: shape=(), dtype=float32, numpy=17.0>

In [52]:
# Convert the output to numpy
tensor[1,0,1].numpy()

17.0

In [54]:
# Lenght or size of a tensor ie number of elements inside the tensor
tf.size(tensor).numpy()

12

In [56]:
tf.transpose(tensor)

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[10., 16.],
        [13., 19.]],

       [[11., 17.],
        [14., 20.]],

       [[12., 18.],
        [15., 21.]]], dtype=float32)>

In [57]:
tf.cast(tensor,dtype = tf.float64)

<tf.Tensor: shape=(2, 2, 3), dtype=float64, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]])>

In [66]:
Tensor = tf.reshape(tensor, shape = (3,4))
Tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[10., 11., 12., 13.],
       [14., 15., 16., 17.],
       [18., 19., 20., 21.]], dtype=float32)>

In [70]:
tf.reduce_mean(Tensor, axis = 0, keepdims = True) # axis = 0 means row wise but the operation happens over the columns

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[14., 15., 16., 17.]], dtype=float32)>

In [69]:
tf.reduce_mean(Tensor, axis = 1) # axis = 1 means col wise but the operation happens over the rows

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([11.5, 15.5, 19.5], dtype=float32)>

In [78]:
dice11 = tf.Variable(tf.random.uniform(shape = (10, 1), minval=1, maxval=7, dtype=tf.int32))
dice12 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
dice_sum1 = dice11 + dice12

In [82]:
tf.concat([dice11, dice12, dice_sum1], axis = 1)

<tf.Tensor: shape=(10, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 1,  2,  3],
       [ 2,  3,  5],
       [ 4,  5,  9],
       [ 6,  1,  7],
       [ 6,  5, 11],
       [ 3,  2,  5],
       [ 5,  6, 11],
       [ 2,  5,  7],
       [ 2,  1,  3]], dtype=int32)>

In [80]:
tf.concat([dice11, dice12, dice_sum1], axis = 0)

<tf.Tensor: shape=(30, 1), dtype=int32, numpy=
array([[ 1],
       [ 1],
       [ 2],
       [ 4],
       [ 6],
       [ 6],
       [ 3],
       [ 5],
       [ 2],
       [ 2],
       [ 2],
       [ 2],
       [ 3],
       [ 5],
       [ 1],
       [ 5],
       [ 2],
       [ 6],
       [ 5],
       [ 1],
       [ 3],
       [ 3],
       [ 5],
       [ 9],
       [ 7],
       [11],
       [ 5],
       [11],
       [ 7],
       [ 3]], dtype=int32)>

Checkpoint in tensorflow

In [84]:
variable1 = tf.Variable([[5,6,9,3],[14,15,16,18]])
checkpoint= tf.train.Checkpoint(var=variable1)
savepath = checkpoint.save('./vars')
variable1.assign([[0,0,0,0],[0,0,0,0]])
variable1
checkpoint.restore(savepath)
print(variable1)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 5,  6,  9,  3],
       [14, 15, 16, 18]], dtype=int32)>
