<a href="https://colab.research.google.com/github/B2BDA/Tensorflow_Basics_Templates/blob/main/Tensorflow_Basics_1_x.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==1.14.0

     |████████████████████████████████| 109.2MB 51kB/s 
     |████████████████████████████████| 3.2MB 45.3MB/s 
     |████████████████████████████████| 491kB 49.0MB/s 
     |████████████████████████████████| 51kB 5.2MB/s 
  Found existing installation: tensorboard 2.3.0
    Uninstalling tensorboard-2.3.0:
      Successfully uninstalled tensorboard-2.3.0
  Found existing installation: tensorflow-estimator 2.3.0
    Uninstalling tensorflow-estimator-2.3.0:
      Successfully uninstalled tensorflow-estimator-2.3.0
  Found existing installation: tensorflow 2.3.0
    Uninstalling tensorflow-2.3.0:
      Successfully uninstalled tensorflow-2.3.0


In [2]:
import tensorflow as tf

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

In [3]:
tf.__version__

'1.14.0'

Define Variables in Tensorflow 1.x

In [4]:
name = 'Bish'

In [5]:
name_tf = tf.constant(name)

In [6]:
name_tf

<tf.Tensor 'Const:0' shape=() dtype=string>

In order to access the variable we need to build a session in tf 1.x
Creating a session means allocating resources
Session builds a precomputed graph




In [7]:
with tf.Session() as sess:
  output = sess.run(name_tf)
  print(output)

b'Bish'


In [8]:
zero_dim_tf = tf.constant(1)
zero_dim_tf

<tf.Tensor 'Const_1:0' shape=() dtype=int32>

In [9]:
one_dim_tf = tf.constant([1,2,3,4])
one_dim_tf

<tf.Tensor 'Const_2:0' shape=(4,) dtype=int32>

In [10]:
two_dim_tf = tf.constant([[1,2,3],[4,5,6]])
two_dim_tf

<tf.Tensor 'Const_3:0' shape=(2, 3) dtype=int32>

In [11]:
three_dim_tf = tf.constant([[[1,2,3],[4,5,6],[7,8,9]]])
three_dim_tf

<tf.Tensor 'Const_4:0' shape=(1, 3, 3) dtype=int32>

In [12]:
with tf.Session() as sess:
  output = sess.run(three_dim_tf)
  print(output)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


Placeholder in tf is used to tell what data type varible it is going to store.
In constant variable we pass the data and we dont change the data as it is constant.

In [13]:
x = tf.placeholder(tf.string)

X will except a string

In [14]:
with tf.Session() as sess:
  output = sess.run(x, feed_dict = {x:'Hello Julia!!! LOL'})
  print(output)

Hello Julia!!! LOL


In [15]:
a = tf.placeholder(tf.string)
b = tf.placeholder(tf.int32)
c = tf.placeholder(tf.float32)

In [16]:
with tf.Session() as sess:
  output1 = sess.run(a, feed_dict={a:"hello",b:124, c:23.32})
  output2 = sess.run(b, feed_dict={a:"hello",b:124, c:23.32})
  output3 = sess.run(c, feed_dict={a:"hello",b:124, c:23.32})
  print(output1, output2, output3)

hello 124 23.32


Tf maths

In [17]:
x = tf.add(5,4) # multiply, substract
with tf.Session() as sess:
  output1 = sess.run(x)
  print(output1)

9


Type casting

In [18]:
sub = tf.subtract(tf.cast(tf.constant(2.0),tf.int32), 1)
with tf.Session() as sess:
  output1 = sess.run(sub)
  print(output1)

1


In [19]:
a = tf.constant(12)
b = tf.constant(3)
c = tf.subtract(tf.divide(a,b),1)
with tf.Session() as sess:
  output1 = sess.run(c)
  print(output1)

3.0


In [20]:
x = tf.Variable(3)

In [21]:
x

<tf.Variable 'Variable:0' shape=() dtype=int32_ref>

In [22]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)

In [23]:
n_feature = 500
n_labels = 5
weights = tf.Variable(tf.truncated_normal((n_feature, n_labels)))
init = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
  w = sess.run(weights)
  print(w)

[[-0.9436226  -0.59523803  1.3903627   0.17943674 -0.25075218]
 [-0.08755967 -0.9247867  -0.79915327 -0.5440635   0.2647459 ]
 [-0.8034311  -1.2235987  -0.36908484  0.2862686  -0.41475126]
 ...
 [-1.0518669  -1.6234721   0.73243165 -1.788566    0.41949436]
 [ 0.21188167  0.049867    0.7676383   0.2798425   0.61186916]
 [-0.33317444 -0.50522864  0.03043741 -0.9283718  -0.4127804 ]]


In [24]:
bias = tf.zeros((500,5))
init = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
  b = sess.run(bias)
  print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Softmax



In [28]:
softmax_act = tf.nn.softmax(tf.cast([2,1,0.2], tf.float32))
with tf.Session() as sess:
  op = sess.run(softmax_act)
  print(op)

[0.65223986 0.23994564 0.10781453]


In [29]:
softmax_act = tf.nn.softmax(tf.cast([1.2,0.9,0.4], tf.float32))
with tf.Session() as sess:
  op = sess.run(softmax_act)
  print(op)

[0.45659032 0.3382504  0.20515925]


In [30]:
import tensorflow as tf
def softmax_activation(logits):
  ''' logits: expects a list '''
  logits = tf.cast(logits, tf.float32)
  softmax_act = tf.nn.softmax(logits)
  with tf.Session() as sess:
    op = sess.run(softmax_act)
    return op

In [32]:
print(softmax_activation([19,354,354,45,354,54]))

[0.         0.33333334 0.33333334 0.         0.33333334 0.        ]


In [48]:
import tensorflow as tf
def softmax_activation(logits, one_hot):
  ''' logits: expects a list
      one_hot: expects a list '''
  logits = tf.cast(logits, tf.float32)
  one_hot = tf.cast(one_hot, tf.float32)
  softmax_act = tf.nn.softmax(logits)
  prod = - tf.reduce_sum(tf.multiply(one_hot, tf.log(logits)))
  with tf.Session() as sess:
    op = sess.run(prod)
    return op

In [49]:
print(softmax_activation([0.7,0.2,0.1],[1,0,0]))

0.35667497
